---
development:
  cloud_name: paulyc
  api_key: '693456347199432'
  api_secret: VVHpx4DjJRX2LcYQ4rO26f73HNE
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: paulyc
  api_key: '693456347199432'
  api_secret: VVHpx4DjJRX2LcYQ4rO26f73HNE
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: paulyc
  api_key: '693456347199432'
  api_secret: VVHpx4DjJRX2LcYQ4rO26f73HNE
  enhance_image_tag: true
  static_image_support: false
